"""Per-test fixture-vault copy. Repo fixtures NEVER mutate."""

from __future__ import annotations

import os
import re
import shutil
import sys
import threading
import time
from pathlib import Path

import pytest
from benchmark_capabilities import (
    declares_absent_directory_fd,
    declares_absent_sandbox,
    declares_absent_surface_timers,
    declares_absent_trusted_git,
    has_bwrap_sandbox,
    has_posix_directory_fd_traversal,
    has_posix_file_modes,
    has_posix_interval_timers,
    has_trusted_system_git,
)

from exomem import activation_manifest as activation_manifest_module
from exomem import embeddings as embeddings_module
from exomem import find as find_module
from exomem import graph_sync as graph_sync_module
from exomem import schema as schema_module
from exomem import semantic_contract as semantic_contract_module

REPO_ROOT = Path(__file__).resolve().parents[1]
FIXTURE_VAULT = REPO_ROOT / "tests" / "fixtures"


def initialize_vault_state_offline(vault_root: Path, *, source: str) -> None:
    """Initialize one explicitly constructed fixture through the offline seam.

    This is deliberately opt-in rather than an autouse repair: tests that
    exercise legacy or unready placement must retain the production refusal.
    """
    from exomem import state_migration

    authority = state_migration.assert_offline_migration_authority(source=source)
    state_migration.migrate_vault_state_offline(vault_root, authority=authority)
    state_migration.reset_state_resolution_cache_for_tests()
    state_migration.require_vault_state_ready(vault_root)


# The benchmark package (benchmarks/membench) deliberately lives outside src/
# and outside the wheel/sdist; tests reach it via this guarded path insert.
_BENCHMARKS_DIR = REPO_ROOT / "benchmarks"
if _BENCHMARKS_DIR.is_dir() and str(_BENCHMARKS_DIR) not in sys.path:
    sys.path.insert(0, str(_BENCHMARKS_DIR))

# POSIX-only by construction. These modules reach `fcntl` or `os.O_DIRECTORY`
# at *import* scope -- `exomem.hosted_restore` and `benchmarks/protocol/custody.py`
# -- so on Windows they abort collection with ImportError rather than skipping,
# and a single unimportable module interrupts the entire run. Declaring them
# here rather than passing `--ignore` on the command line keeps `pytest` one
# command on every platform, for CI and for a developer on Windows alike.
#: `benchmarks/protocol/custody.py` is a *Linux* capability, not merely POSIX
#: code. It builds directory custody on proc-fd magic symlinks: `capability_path`
#: is `/proc/self/fd/<n>`, and both the module and its callers path-walk through
#: it -- `capability_path / "child"`, `.iterdir()`, `symlink_to`. macOS has no
#: `/proc`, and its `/dev/fd/<n>` is not a substitute: fdesc resolves the fd
#: itself but supports no directory lookup, so `/dev/fd/<n>/child` cannot
#: resolve. The module already says this itself by raising `CustodyUnsupported`
#: rather than degrading into a weaker guarantee.
PROC_FD_DIRECTORY_CUSTODY = os.name == "posix" and Path("/proc/self/fd").is_dir()

collect_ignore: list[str] = []
if os.name == "nt":
    collect_ignore += [
        "test_dataset_identity_case_count.py",  # -> lme.runner -> protocol.custody
        "test_hosted_restore_candidate.py",  # -> exomem.hosted_restore -> fcntl
        "test_lme_reader_gate.py",  # -> lme.runner -> protocol.custody
        "test_lme_runner.py",  # -> lme.runner -> protocol.custody
        "test_protocol_custody.py",  # imports fcntl directly
        # Same subsystem, same reason, and the list was simply incomplete: these
        # import `protocol.custody` inside the test body rather than at module
        # scope, so collection succeeded and they failed one by one at run time
        # instead of being declared unsupported here. On Windows the custody
        # capability blocks them almost entirely -- 17/17, 8/8, 3/3, 1/1, 11/11
        # and 75 of 83 -- so ignoring the file costs a handful of cases in a
        # subsystem this platform cannot run, which is the trade the entries
        # above already make.
        "test_lme_basic_memory_direct.py",
        "test_lme_cli_provider_choices.py",
        "test_lme_direct_lifecycle.py",
        "test_lme_hybrid_rag.py",
        "test_lme_providers.py",
        "test_lme_runner_protocol.py",
        "test_protocol_manifest_trace.py",
    ]

# --- CI tier selection (`.github/workflows/ci.yml`) -------------------------
# The PR suite runs as two sharded tiers: `core` (everything below minus the
# benchmark-harness modules minus the nightly-owned latency gate) and
# `harness` (exactly the modules in tests/harness_modules.txt, generated by
# scripts/generate_harness_modules.py). With EXOMEM_TEST_TIER unset — local
# runs, cross-platform CI, the nightly latency job — collection is exactly
# what it always was. tests/test_ci_reliability_contract.py pins the module
# list against its derivation and proves core ∪ harness ∪ latency equals the
# full collection, so a tier defect here reads as red rather than as lost
# coverage.
_HARNESS_MODULES_FILE = Path(__file__).with_name("harness_modules.txt")
#: Owned by the nightly `retrieval-latency` job; runs in neither PR tier.
_NIGHTLY_OWNED_MODULES = ("test_latency_gate.py",)
_TEST_TIER = os.environ.get("EXOMEM_TEST_TIER", "").strip()
if _TEST_TIER:
    if _TEST_TIER not in {"core", "harness"}:
        raise RuntimeError(
            f"EXOMEM_TEST_TIER={_TEST_TIER!r} is not a CI tier; use 'core' or 'harness'"
        )
    # A missing list must fail the run loudly: falling back to "collect
    # everything" would run the full suite in both tiers and still show green.
    _harness_modules = [
        line.strip().removeprefix("tests/")
        for line in _HARNESS_MODULES_FILE.read_text(encoding="utf-8").splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]
    if _TEST_TIER == "core":
        collect_ignore += _harness_modules
        collect_ignore += list(_NIGHTLY_OWNED_MODULES)
    else:
        _keep = set(_harness_modules)
        for _entry in sorted(Path(__file__).parent.iterdir()):
            if _entry.name == "conftest.py" or _entry.name in _keep:
                continue
            if _entry.is_dir():
                if not any(kept.startswith(f"{_entry.name}/") for kept in _keep):
                    collect_ignore.append(_entry.name)
            elif _entry.suffix == ".py" and _entry.name.startswith("test_"):
                collect_ignore.append(_entry.name)


#: `custody.py` walks a path as POSIX components -- `parts[0] != os.sep`, then a
#: backslash test on every remaining part -- so on Windows *every* custody path
#: trips one of these before the module reaches its own capability check.
#: Neither message is then describing the path it names. Both remain real
#: findings on a platform that has the capability, which is why matching them is
#: gated on it being absent.
_CUSTODY_ALIEN_PATH = re.compile(
    r"custody path (must identify a non-root directory|contains an unsafe component)"
)


def _declares_custody_unsupported(error: BaseException | None) -> bool:
    """True when *error* is the custody module refusing an absent capability.

    Matched by qualified name rather than by importing `protocol.custody`: on
    Windows that import is itself one of the things that fails, and a hook that
    needs the module in order to decide whether the module is usable is no hook
    at all.
    """
    seen: set[int] = set()
    while error is not None and id(error) not in seen:
        seen.add(id(error))
        if type(error).__name__ == "CustodyUnsupported":
            return True
        if type(error).__name__ == "CustodyError" and _CUSTODY_ALIEN_PATH.search(str(error)):
            return True
        error = error.__cause__ or error.__context__
    return False


#: `custody.py` says this exact sentence when it finds no procfs. It reaches a
#: test as text rather than as a raised error in the `assert <exception> is
#: <expected>` cases, where the refusal is the *value* being compared, so the
#: qualified-name walk above cannot see it.
_CUSTODY_PROC_FD_DECLARATION = re.compile(
    r"POSIX proc-fd directory capabilities are unavailable"
)


def _needs_an_absent_procfs(error: BaseException | None) -> bool:
    """True when *error* is a custody test reaching `/proc` on a host without one.

    Several of these tests read `/proc/self/fd` or a `/proc/<pid>/fd/<n>/...`
    capability path directly rather than through `custody.py`, so they never
    reach the module's own declaration -- and the lifecycle runner wraps what
    it caught in `LifecycleRunError`, which buries it further. In both shapes
    the original `FileNotFoundError` survives on the cause chain and names the
    path it could not find.

    A missing file under `/proc` on a host with no procfs is not ambiguous: the
    file is absent because the filesystem that would supply it was never
    mounted. Gated by the caller on that being the case, so on Linux -- where
    `ci.yml` runs and procfs exists -- a missing `/proc` entry stays a failure.
    """
    seen: set[int] = set()
    while error is not None and id(error) not in seen:
        seen.add(id(error))
        if isinstance(error, OSError):
            filename = getattr(error, "filename", None)
            if isinstance(filename, str) and filename.startswith("/proc/"):
                return True
        if _CUSTODY_PROC_FD_DECLARATION.search(str(error)):
            return True
        error = error.__cause__ or error.__context__
    return False


#: POSIX-only standard-library surfaces the hosted cell runtime is built on.
#: A hosted cell is a Linux container: it checks its own effective uid before
#: trusting a runtime path, and takes `fcntl` locks on its state. There is no
#: Windows behaviour for those to differ from -- the API does not exist -- so a
#: test that reaches one is describing Linux, not failing on Windows.
_POSIX_ONLY_API = re.compile(
    r"module 'os' has no attribute 'gete?uid'"
    r"|<module 'os'[^>]*> has no attribute 'gete?uid'"
    # The hosted operator scripts open every input `O_NOFOLLOW` and every
    # directory `O_DIRECTORY` so a symlink swapped in mid-read cannot
    # redirect them. Windows publishes neither flag, so the scripts cannot
    # even be loaded there -- and they only ever run on the Linux cell.
    r"|module 'os' has no attribute 'O_(?:NOFOLLOW|DIRECTORY)'"
    r"|<module 'os'[^>]*> has no attribute 'O_(?:NOFOLLOW|DIRECTORY)'"
    r"|No module named 'fcntl'"
)


def _needs_an_absent_posix_api(error: BaseException | None) -> bool:
    """True when *error* is this platform simply not having a POSIX API.

    Narrow by construction: only `AttributeError` for the uid calls and
    `ModuleNotFoundError` for `fcntl` count, and only their exact messages. An
    ordinary `AttributeError` from a typo or a renamed attribute does not match,
    so this cannot quietly absorb a real defect into a skip.
    """
    seen: set[int] = set()
    while error is not None and id(error) not in seen:
        seen.add(id(error))
        if isinstance(error, (AttributeError, ImportError)) and _POSIX_ONLY_API.search(
            str(error)
        ):
            return True
        error = error.__cause__ or error.__context__
    return False


#: The hosted cell proves its state is private with POSIX ownership and mode
#: bits -- `st_uid`/`st_gid` against the runtime owner, `0o700` on the state
#: root, `0o600` on the security database, and a `mkdir(mode=0o700)` to create
#: it. Windows has none of that as an access-control fact: it reports no owner
#: ids and synthesizes a mode, so a directory reads `0o777` and a file `0o666`
#: whatever `chmod` was asked for. Every one of these refusals is that check
#: reading a placeholder and correctly declining to vouch for it.
#:
#: The DACL refusal belongs to the same fact from the other side. Because the
#: bare `mkdir` above leaves an ordinary inherited DACL on Windows, the
#: idempotency runtime under the same state root -- which does have a native
#: Windows implementation, and requires a *protected* DACL it created itself --
#: refuses the directory the cell just made. The two only disagree on Windows;
#: on Linux `prepare_windows_private_state_root` is a no-op and
#: `mkdir(mode=0o700)` is genuinely private, so there is nothing to reconcile
#: for the platform this component is deployed on. A hosted cell is a Linux
#: container, which is the same reason `test_hosted_restore_candidate.py` is
#: ignored outright here.
_HOSTED_POSIX_OWNERSHIP_REFUSAL = (
    "HostedSecurityStateInvalid",
    "HostedSecurityUnavailable",
    "HostedRuntimeTempUnavailable",
    "WindowsRuntimeDaclError",
)
_HOSTED_TEMP_REFUSAL = re.compile(r"hosted runtime temp is unavailable")

#: The hosted operator scripts refuse any input whose POSIX mode they cannot
#: vouch for. Windows `chmod` only toggles a read-only bit, so it cannot
#: express 0600 or the absence of group/world write at all, and the scripts
#: are correct to refuse. Matched on the sentences that name a mode, never on
#: a bare refusal type, so a genuine path-safety finding still fails.
_HOSTED_OPERATOR_MODE_REFUSAL = re.compile(
    r"must be a non-writable regular file"
    r"|without group/world write access"
    r"|must have mode 0600"
)


def _needs_posix_ownership_semantics(error: BaseException | None) -> bool:
    """True when *error* is the hosted cell declining to trust a synthesized mode.

    Matched by the refusal types the cell raises for exactly this, never on a
    bare `OSError`, and gated by the caller on the platform genuinely lacking
    POSIX file modes -- so on Linux CI, where the cell actually runs, every one
    of these stays a failure.
    """
    seen: set[int] = set()
    while error is not None and id(error) not in seen:
        seen.add(id(error))
        if type(error).__name__ in _HOSTED_POSIX_OWNERSHIP_REFUSAL:
            return True
        if _HOSTED_TEMP_REFUSAL.search(str(error)):
            return True
        if _HOSTED_OPERATOR_MODE_REFUSAL.search(str(error)):
            return True
        error = error.__cause__ or error.__context__
    return False


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):  # noqa: ANN001, ANN201
    """Report a platform capability this host does not have as a skip.

    Five causes now, every one of them "this API does not exist here" rather
    than "this code is wrong". They were reported as defects when the honest
    report was that the platform cannot run the subsystem.

    On macOS, 82 of them were one platform fact: the capability
    `protocol.custody` is built on does not exist there, and the module says so
    in the way it was designed to. A missing capability is what `skip` means.

    Deliberately *not* `collect_ignore` here, which is why macOS is handled
    differently from Windows above. These modules are only *partly* custody
    -dependent on macOS -- it collects 162 tests from `test_lme_direct_lifecycle`
    and only 50 of them need proc-fd -- so ignoring whole files to silence the
    minority would drop 100+ tests that pass and genuinely cover this platform.
    Windows is the opposite case: there the same files are blocked almost
    entirely, so ignoring them costs nearly nothing and buys a declaration.

    The two broker branches are the same trade for different capabilities, and
    they are separate because the platforms differ: Windows has neither, but
    macOS has POSIX interval timers and no `bwrap` at all. The sandbox is not
    merely "Linux" either -- the broker pins `/usr/bin/bwrap` and binds
    `/usr/bin/python3.12`, `/lib/x86_64-linux-gnu` and
    `/lib64/ld-linux-x86-64.so.2` into the namespace, so the capability is that
    exact Debian x86-64 runtime.
    `epistemic.broker` bounds every provider surface with `setitimer`/`SIGALRM`,
    isolates it with that sandbox, and refuses up front where either is absent.
    Its entry points share no helper to gate, so each refusal is matched where it
    surfaces -- through `__context__` as well, because `pytest.raises(...,
    match=...)` re-raises as an `AssertionError` holding it: a test that expected
    one contract error and met a refusal instead failed for the absent
    capability, not for its own reason.

    The Git branch is the same trade again. `benchmarks/protocol` resolves Git
    through `os.defpath` rather than `PATH`, so a user-controlled `PATH` cannot
    substitute the binary that establishes contract identity -- but `os.defpath`
    on Windows names a drive-root `bin` directory that does not exist, behind
    the very current-directory entry the anchor exists to exclude. Only the
    three refusals meaning "the anchor found nothing usable" are matched; a
    digest mismatch stays a failure, because that is a real finding.

    Every branch is gated on the capability actually being absent, so this can
    never mask a regression where it matters: on Linux CI all of them exist --
    `ci.yml` provisions `bwrap` and checks it runs, and `/usr/bin` is on
    `os.defpath` -- so a `CustodyUnsupported`, a timer refusal, a sandbox
    refusal or a Git refusal there stays a failure and is meant to.
    """
    report = (yield).get_result()
    # `setup` as well as `call`: a fixture that builds its subject through the
    # absent capability raises before the body runs, and an error there is the
    # same missing prerequisite reported one phase earlier.
    if report.when not in {"call", "setup"} or report.outcome != "failed":
        return
    if call.excinfo is None:
        return
    error = call.excinfo.value
    if not PROC_FD_DIRECTORY_CUSTODY and (
        _declares_custody_unsupported(error) or _needs_an_absent_procfs(error)
    ):
        reason = "proc-fd directory custody is unavailable on this platform"
    elif os.name == "nt" and _needs_an_absent_posix_api(error):
        reason = "the hosted cell runtime's POSIX APIs do not exist on Windows"
    elif not has_posix_file_modes() and _needs_posix_ownership_semantics(error):
        reason = "the hosted cell proves state privacy with POSIX ownership this platform lacks"
    elif not has_posix_interval_timers() and declares_absent_surface_timers(error):
        reason = "POSIX interval timers (setitimer/SIGALRM) are unavailable here"
    elif not has_bwrap_sandbox() and declares_absent_sandbox(error):
        reason = "the pinned bubblewrap sandbox runtime is unavailable here"
    elif not has_trusted_system_git() and declares_absent_trusted_git(error):
        reason = "os.defpath names no trusted system Git on this platform"
    elif not has_posix_directory_fd_traversal() and declares_absent_directory_fd(error):
        reason = "POSIX directory descriptors (openat) do not exist on this platform"
    else:
        return
    report.outcome = "skipped"
    report.longrepr = (str(item.path), item.location[1] or 0, f"Skipped: {reason}")


@pytest.fixture(autouse=True)
def _stop_leaked_graph_drain():
    """No test leaves the graph drain daemon running into the next one.

    `server_runtime` starts it and nothing stops it, so any test that exercises
    server startup leaks the thread for the rest of the session. It then keeps
    polling a vault root whose `tmp_path` has been deleted, and it turns up in
    every later thread dump -- including the one from the `windows-latest`
    shard that hangs, where it was the first suspect precisely because it was
    the only unexplained thread there.

    The daemon is idle-waiting and almost certainly innocent, but a leaked
    thread that outlives its vault has no business being a variable in someone
    else's failure. This is the same hazard the rebuild threads already have on
    record for crossing test boundaries.
    """
    yield
    from exomem import graph_drain

    graph_drain.stop()
    graph_drain._DEBT.clear()


#: Captured before any test can instrument the filesystem primitives: the
#: guard below runs in autouse teardown, after test-scoped patches of
#: `os.scandir`/`os.lstat` may still be mid-unwind, and the guard's own probe
#: of the REAL platform root must never route through them. The `/proc` scan
#: below extends the same discipline to its own primitives -- deliberately
#: plain `os` calls rather than `pathlib.Path` methods, so a test patching
#: `Path.iterdir`/`Path.read_bytes`/`Path.is_dir` cannot pollute or stall the
#: triage scan either.
_REAL_SCANDIR = os.scandir
_REAL_LSTAT = os.lstat
_REAL_OS_OPEN = os.open
_REAL_OS_READ = os.read
_REAL_OS_CLOSE = os.close
_REAL_OS_READLINK = os.readlink
_REAL_OS_PATH_ISDIR = os.path.isdir


def _state_root_shallow_snapshot(root: Path) -> tuple:
    """A cheap fingerprint of the real user state root: existence, the root's
    own mtime, and its immediate children. Deep content writes into a
    pre-existing per-vault directory escape this — the primary isolation is
    the injected EXOMEM_STATE_ROOT; this guard is belt-and-braces against a
    consumer that composes the real platform root itself."""
    try:
        info = _REAL_LSTAT(root)
    except OSError:
        return ("absent",)
    try:
        children = tuple(
            sorted((entry.name, entry.stat().st_mtime_ns) for entry in _REAL_SCANDIR(root))
        )
    except OSError:
        children = ("unreadable",)
    return ("present", info.st_mtime_ns, children)


def _state_root_drift_summary(before: tuple, after: tuple) -> str:
    """A legible description of what changed between two
    :func:`_state_root_shallow_snapshot` results, by entry name.

    Split out from the assert purely for testability -- this function makes
    no pass/fail decision and the guard's own comparison stays `after ==
    before`, unchanged, regardless of what this reports. Four incidents on
    2026-08-29 alone showed a triager the raw snapshot tuples
    (`before=('present', 1788012082470890197, ...)`) and nothing else; naming
    the added/removed/mtime-shifted entries is the whole point.
    """
    if before == after:
        return "no drift detected"
    before_present = before[0] == "present"
    after_present = after[0] == "present"
    if before_present and not after_present:
        return "the root existed before and is gone now"
    if after_present and not before_present:
        return "the root did not exist before and exists now"
    if not before_present and not after_present:
        # Both "absent" yet the tuples differ, or one/both is some other
        # sentinel shape entirely -- say so rather than guessing.
        return f"before={before!r} after={after!r}"
    before_children = before[2]
    after_children = after[2]
    if before_children == ("unreadable",) or after_children == ("unreadable",):
        return "the root's children became readable/unreadable between snapshots"
    before_map = dict(before_children)
    after_map = dict(after_children)
    added = sorted(set(after_map) - set(before_map))
    removed = sorted(set(before_map) - set(after_map))
    changed = sorted(
        name for name in set(before_map) & set(after_map) if before_map[name] != after_map[name]
    )
    parts = []
    if added:
        parts.append("added: " + ", ".join(added))
    if removed:
        parts.append("removed: " + ", ".join(removed))
    if changed:
        parts.append("changed: " + ", ".join(changed))
    if not parts:
        return "the root directory's own mtime changed with no child differences"
    return "; ".join(parts)


def _read_proc_file(path: str, max_bytes: int = 4096) -> bytes | None:
    """Read a `/proc` pseudo-file through import-time-captured `os`
    primitives only -- never `pathlib.Path`, per the module header note.

    Never raises: any failure (process exited mid-read, permission denied,
    the path never existed) reports as "nothing read" to the caller, which is
    always a best-effort triage consumer.
    """
    fd = None
    try:
        fd = _REAL_OS_OPEN(path, os.O_RDONLY)
        return _REAL_OS_READ(fd, max_bytes)
    except OSError:
        return None
    finally:
        if fd is not None:
            try:
                _REAL_OS_CLOSE(fd)
            except OSError:
                pass


def _process_ancestor_pids(start_pid: int) -> frozenset[int]:
    """Every pid from `start_pid`'s parent up to pid 1, via `/proc/<pid>/stat`.

    CI always runs pytest under a wrapper (`uv run ... python -m pytest`), so
    the running process's own ancestor chain matches "pytest"/"exomem" on
    every single run -- without exclusion, `_concurrent_process_candidates`
    would report a "concurrent" hit unconditionally and mislead every
    triager, every run, regardless of whether anything is actually
    interfering.

    `stat`'s comm field (2nd column, in parens) can itself contain spaces or
    parens, so ppid is located from the LAST ')' rather than by naive
    whitespace-splitting (proc(5)): the whitespace-separated fields after it
    are state, ppid, pgrp, ... -- ppid is the 2nd of those.

    Best-effort like the scan it supports: any failure simply stops the walk
    where it is, returning whatever ancestors were already found.
    """
    ancestors: set[int] = set()
    seen = {start_pid}
    pid = start_pid
    for _ in range(4096):  # hard cap: never loop forever on a corrupt chain
        raw = _read_proc_file(f"/proc/{pid}/stat")
        if not raw:
            break
        text = raw.decode("utf-8", "replace")
        close = text.rfind(")")
        if close == -1:
            break
        fields = text[close + 1 :].split()
        if len(fields) < 2:
            break
        try:
            ppid = int(fields[1])
        except ValueError:
            break
        if ppid <= 0 or ppid in seen:
            break
        ancestors.add(ppid)
        seen.add(ppid)
        if ppid == 1:
            break
        pid = ppid
    return frozenset(ancestors)


def _best_effort_proc_cwd(pid: int) -> str:
    """The best-effort cwd of `pid` -- the actually-useful triage datum (which
    worktree's run this is) -- never the full argv."""
    try:
        return _REAL_OS_READLINK(f"/proc/{pid}/cwd")
    except OSError:
        return "unknown"


def _matching_processes(exclude: frozenset[int]) -> tuple[tuple[int, str], ...]:
    """All ``(pid, cmdline)`` for live processes outside ``exclude`` whose
    cmdline contains "pytest" or "exomem".

    Uncapped and unredacted -- :func:`_concurrent_process_candidates` applies
    the cap and redaction on top of this. Split out so ancestor-exclusion and
    third-party-detection can be tested directly, without the cap's
    iteration-order sensitivity (``/proc`` readdir order is not guaranteed,
    so which matches survive a cap is not deterministic on a busy box).

    Per-entry failures are caught individually so one uncooperative ``/proc``
    entry does not discard matches already found; the directory iteration
    itself is wrapped a second time for the same reason.
    """
    if os.name != "posix":
        return ()
    found: list[tuple[int, str]] = []
    try:
        if not _REAL_OS_PATH_ISDIR("/proc"):
            return ()
        for entry in _REAL_SCANDIR("/proc"):
            try:
                if not entry.name.isdigit():
                    continue
                pid = int(entry.name)
                if pid in exclude:
                    continue
                raw = _read_proc_file(f"/proc/{pid}/cmdline")
                if not raw:
                    continue
                cmdline = raw.replace(b"\x00", b" ").strip().decode("utf-8", "replace")
                if not cmdline:
                    continue
                if "pytest" in cmdline or "exomem" in cmdline:
                    found.append((pid, cmdline))
            except Exception:  # noqa: BLE001 -- one entry's failure must not discard matches already found; this scan is best-effort triage, never load-bearing for the assert.
                continue
    except Exception:  # noqa: BLE001 -- the whole scan is best-effort triage; a failure here returns whatever was already collected rather than aborting the guard itself.
        pass
    return tuple(found)


#: Redacted candidate lines are capped; overflow is summarized rather than
#: silently truncated.
_CONCURRENT_CANDIDATE_CAP = 5


def _candidate_exclusion_pids() -> frozenset[int]:
    """The pids the candidate scan must never report: this process and its
    full ancestor chain. Extracted as a named seam so a test can pin the
    exclusion-set CONSTRUCTION itself -- absence from a capped render proves
    nothing, and a weakened set here is exactly the mutation review caught.
    """
    own_pid = os.getpid()
    return frozenset(_process_ancestor_pids(own_pid) | {own_pid})


def _concurrent_process_candidates() -> tuple[str, ...]:
    """Best-effort `/proc` scan for other live pytest/exomem processes.

    Purely diagnostic triage, never load-bearing for the assert: the state
    root is machine-global, so another worktree's pytest, a stray `-x` run,
    or a foreign tmpdir can all trip the guard on files this diff never
    touched. Deliberately POSIX-only (`/proc` has no Windows analogue) and
    never raises -- a scan that finds nothing and a scan that fails outright
    are reported identically by the caller (as "unavailable"), so a bare
    empty tuple is the right shape for both.

    Redaction: only the pid, the basename of argv[0], and a best-effort cwd
    are ever reported -- never the raw argv line, which can carry secrets (an
    ssh private-key path was captured live in review off an earlier,
    unredacted render). The scan's own ancestor chain
    (:func:`_process_ancestor_pids`) is excluded so a run's own `uv run ...
    python -m pytest` wrapper never reports itself as "concurrent".
    """
    if os.name != "posix":
        return ()
    matches = _matching_processes(_candidate_exclusion_pids())
    found = []
    for pid, cmdline in matches[:_CONCURRENT_CANDIDATE_CAP]:
        argv0 = cmdline.split(" ", 1)[0]
        basename = argv0.rsplit("/", 1)[-1] or argv0
        cwd = _best_effort_proc_cwd(pid)
        found.append(f"pid {pid}: {basename} (matched: pytest|exomem, cwd: {cwd})")
    if len(matches) > _CONCURRENT_CANDIDATE_CAP:
        found.append(f"(+{len(matches) - _CONCURRENT_CANDIDATE_CAP} more)")
    return tuple(found)


_STATE_ROOT_GUARD_TRIAGE_HINT = (
    "this also fires for cross-process interference, not just this diff: "
    "another worktree's pytest, a stray -x run, or a foreign tmpdir can "
    "touch this same machine-global root; check for concurrent pytest/exomem "
    "processes and rerun this file solo before attributing the failure to "
    "the code under test."
)


def _state_root_guard_message(real_root: Path, before: tuple, after: tuple) -> str:
    """The guard's full assertion message: legible attribution first, the
    triage hint, best-effort concurrent-process candidates, then the raw
    snapshot tuples last (kept available, but secondary)."""
    drift = _state_root_drift_summary(before, after)
    candidates = _concurrent_process_candidates()
    candidates_text = "; ".join(candidates) if candidates else "unavailable"
    return (
        f"a test touched the real user state root {real_root} ({drift}); "
        "every fixture must stay under the injected EXOMEM_STATE_ROOT tmpdir. "
        f"{_STATE_ROOT_GUARD_TRIAGE_HINT} "
        f"concurrent candidates: {candidates_text}. "
        f"raw snapshot (before={before!r}, after={after!r})"
    )


@pytest.fixture(scope="session", autouse=True)
def _isolate_state_root_for_session(tmp_path_factory: pytest.TempPathFactory):
    """A higher-scoped fixture must not write the real user state root either.

    `_isolate_state_root` below is function-scoped, so it is simply not in
    effect while a module- or session-scoped fixture *body* runs. One that
    builds a vault there resolves `state_paths.state_store_root()` with no
    override and writes the REAL platform root:
    `tests/test_graph_value_benchmark.py`'s module-scoped `perfect_fixture`
    did exactly that, leaving `<slug>-<digest>/.graph.sqlite` behind for the
    rest of the session. Nothing failed at the point of the write, because no
    function-scoped guard bracketed it; a later test that touched the same
    directory inherited the assertion and was reported as the culprit.

    Injecting at session scope also closes the window *between* tests. The
    function-scoped guard's `undo()` now restores this session value instead
    of unsetting the variable, so a write from a worker that outlived the test
    that started it lands in a tmpdir rather than the user's real state root.

    Deliberately a PRIVATE MonkeyPatch, for the reason the function-scoped
    fixture documents: the shared `monkeypatch` object is function-scoped and
    cannot hold a session-scoped patch anyway.
    """
    private = pytest.MonkeyPatch()
    session_root = tmp_path_factory.mktemp("exomem-session-state-root")
    private.setenv("EXOMEM_STATE_ROOT", str(session_root))
    private.setenv(
        "EXOMEM_WRITER_LEASE_STATE_DIR",
        str(session_root / "writer-lease"),
    )
    try:
        yield
    finally:
        private.undo()


@pytest.fixture(autouse=True)
def _isolate_state_root(tmp_path: Path):
    """No test writes the real user state root (task 1.5 of
    relocate-machine-local-state, mirroring the EXOMEM_VAULT_PATH rule below).

    Every test runs with EXOMEM_STATE_ROOT injected at a unique sibling of its
    tmp_path. The sibling is load-bearing: many tests use tmp_path itself as a
    vault, so nesting the state root below it violates the production placement
    boundary and makes those tests fail for the fixture's topology. The guard
    then asserts the real platform default root was not touched: a consumer
    that composes %LOCALAPPDATA%/XDG itself instead of consulting the
    `state_paths` seam would write outside the injected root and trip it.

    Deliberately a PRIVATE MonkeyPatch instance: the function-scoped
    `monkeypatch` fixture is one shared object, so a test that calls
    `monkeypatch.undo()` mid-test (several do) would strip this isolation
    along with its own patches and re-point the placement seam at the real
    platform root for the rest of the test.
    """
    private = pytest.MonkeyPatch()
    state_root = tmp_path.with_name(f"{tmp_path.name}-exomem-state-root")
    private.setenv("EXOMEM_STATE_ROOT", str(state_root))
    private.setenv(
        "EXOMEM_WRITER_LEASE_STATE_DIR",
        str(state_root / "writer-lease"),
    )
    writer_lease_module = None
    try:
        try:
            from exomem import state_paths, writer_lease
        except ImportError:
            # Red-first window: the seam module does not exist yet, so nothing
            # can resolve the real platform root through it either.
            yield
            return
        writer_lease_module = writer_lease
        writer_lease.reset_managers_for_tests()
        real_root = state_paths.platform_default_state_root()
        before = _state_root_shallow_snapshot(real_root)
        yield
        after = _state_root_shallow_snapshot(real_root)
        assert after == before, _state_root_guard_message(real_root, before, after)
    finally:
        if writer_lease_module is not None:
            writer_lease_module.reset_managers_for_tests()
        private.undo()


@pytest.fixture(autouse=True)
def _process_env_isolation():
    """Restore os.environ after every test.

    Benchmark adapters apply EXOMEM_* profile pins to the process env, and a
    test that drives setup() without a paired cleanup() leaks them into every
    later test: PR #390's CI failed six query-log/usage-ranking tests because
    a stale EXOMEM_VAULT_PATH and EXOMEM_DISABLE_RELEVANCE_CHECK survived from
    an earlier adapter test — failures invisible in isolation and under -k
    filters. Autouse setup runs before test-requested fixtures, so this
    teardown runs after monkeypatch undo and restores the pre-test
    environment exactly.
    """
    saved = os.environ.copy()
    yield
    for key in set(os.environ) - set(saved):
        del os.environ[key]
    for key, value in saved.items():
        if os.environ.get(key) != value:
            os.environ[key] = value


@pytest.fixture(autouse=True)
def _reset_corpus_context_cache():
    """Every test starts with a cold corpus-context cache.

    The cache invalidates on filesystem changes, which production writes
    always make; tests additionally monkeypatch corpus-affecting internals
    (access tiers, registries, walks), which no filesystem census can see.
    A per-test reset keeps such patches from serving a context built under a
    different test's (or an unpatched) environment.
    """
    semantic_contract_module.reset_corpus_context_cache()
    activation_manifest_module.reset_manifest_cache()
    yield
    semantic_contract_module.reset_corpus_context_cache()
    activation_manifest_module.reset_manifest_cache()


#: The single thread name every graph rebuild runs under, in both the
#: registered-flight path (`graph_sync.GraphRebuildCoordinator.ensure_started`)
#: and the warming path (`epistemic_graph.schedule_background_rebuild`).
_GRAPH_REBUILD_THREAD_NAME = "exomem-graph-rebuild"
#: A rebuild over most test vaults is milliseconds, and one that cannot finish
#: has wedged rather than slowed -- worth failing on rather than leaving for
#: whichever test inherits it. But most is not every: the planning-governance
#: cap fixtures build a vault of ~2000 pages, whose whole-vault rebuild
#: measures ~36 s on an idle Windows box, so 30 s reported a rebuild that was
#: progressing normally as wedged and failed the Windows lane in teardown of a
#: test that had passed.
#:
#: Raised well past that measurement rather than tuned to it. A wedged rebuild
#: never finishes, so this value does not decide whether one is caught -- only
#: how long a working rebuild is given before it is libelled, and the cost of
#: guessing low is a false failure in someone else's lane.
#:
#: That a routine rebuild is O(vault) at all is #576; when repair becomes
#: proportional to the change, this can come back down.
_GRAPH_QUIESCE_TIMEOUT_SECONDS = 180.0


def _drain_graph_rebuild_threads(timeout: float = _GRAPH_QUIESCE_TIMEOUT_SECONDS) -> None:
    """Join every graph rebuild still running, and say so if one will not stop.

    The clock is read only once there is something to wait for. This is autouse
    teardown, so it runs after *every* test, and a test is entitled to replace
    `time.monotonic` with a scripted sequence of its own -- one does. Charging
    the empty case a clock read exhausted that sequence and failed the test in
    teardown with `generator raised StopIteration`, from a fixture that had
    nothing to drain.
    """
    deadline: float | None = None
    while True:
        alive = [
            thread
            for thread in threading.enumerate()
            if thread.name == _GRAPH_REBUILD_THREAD_NAME and thread.is_alive()
        ]
        if not alive:
            return
        if deadline is None:
            deadline = time.monotonic() + timeout
        remaining = deadline - time.monotonic()
        if remaining <= 0:
            raise RuntimeError(
                f"{len(alive)} graph rebuild thread(s) did not finish within "
                f"{timeout:.0f}s; a wedged rebuild must not be inherited by the next test"
            )
        for thread in alive:
            thread.join(timeout=max(0.0, deadline - time.monotonic()))


@pytest.fixture(autouse=True)
def _quiesce_graph_rebuilds():
    """Let no graph rebuild outlive the test that started it.

    Production runs one long-lived process against one vault. The suite runs
    many vaults through one process, and since an interactive write stopped
    joining its rebuild (#576) that rebuild is a daemon thread which outlives
    the request -- and therefore, here, the test. It then keeps touching
    process-global projections (`find.unload_ram_caches`, the shared resolver
    and corpus-context caches) while the *next* test is already running against
    a different vault. That is not a race the production shape has; it is an
    artefact of the suite's process sharing.

    Draining at teardown restores the isolation the write's join used to
    provide by accident, without putting that wait back on the write path.
    `graph_sync` coordinators are dropped afterwards so a suite of thousands of
    vaults does not retain one coordinator per vault for the whole run.

    Deliberately not a convergence helper: a test that needs the graph to be
    current asserts that for itself with `graph_sync.await_active_rebuild`.
    This fixture only guarantees that nothing is still running.
    """
    yield
    try:
        _drain_graph_rebuild_threads()
    finally:
        with graph_sync_module._COORDINATORS_LOCK:
            graph_sync_module._COORDINATORS.clear()


@pytest.fixture(autouse=True)
def _disable_embeddings(monkeypatch: pytest.MonkeyPatch, tmp_path: Path) -> None:
    """Skip the heavy bge-base load by default in the test suite.

    Individual tests that exercise embeddings (test_hybrid_search.py)
    delete this env var via their own monkeypatch.
    """
    monkeypatch.setenv("EXOMEM_DISABLE_EMBEDDINGS", "1")
    # Isolate compute-mode resolution from the developer's real ~/.exomem/config.json
    # and any ambient EXOMEM_MODE/EXOMEM_DEVICE — the suite must resolve to the
    # `normal` default deterministically (device selection now consults mode.py).
    monkeypatch.setenv("EXOMEM_CONFIG_PATH", str(tmp_path / "no-such-exomem-config.json"))
    for _var in (
        "EXOMEM_MODE",
        "EXOMEM_QUIET_MODE",
        "EXOMEM_DEVICE",
        "EXOMEM_GPU_MIN_FREE_GB",
        # Model residency policy derives from these; an ambient value would otherwise
        # move `mode.resolved()`, `status.models`, and the reaper's decision.
        "EXOMEM_PRELOAD_MODELS",
        "EXOMEM_RELEASE_GPU_WHEN_IDLE",
        "EXOMEM_MODEL_OFFLINE",
    ):
        monkeypatch.delenv(_var, raising=False)
    monkeypatch.setenv("EXOMEM_DISABLE_RELEVANCE_CHECK", "1")
    # Never spawn the background warm thread from build_server in tests — it
    # would outlive the per-test tmp vault. Warm/readiness tests manage their
    # own env + readiness.reset().
    monkeypatch.setenv("EXOMEM_DISABLE_WARMUP", "1")
    # A committed repo-root ranking_config.json must never perturb the suite:
    # force find()'s adopted-config seam to DEFAULT_RANKING. Tests that exercise
    # the load seam delete this var via their own monkeypatch.
    monkeypatch.setenv("EXOMEM_DISABLE_RANKING_CONFIG", "1")
    # No real ASR/OCR in the suite: keep uploads from enqueuing GPU work. Tests that
    # exercise the worker enable it explicitly and stub extract.extract_text.
    monkeypatch.setenv("EXOMEM_DISABLE_MEDIA_EXTRACTION", "1")
    # No real CLIP either; tests that exercise it stub embeddings.embed_image/embed_clip_text.
    monkeypatch.setenv("EXOMEM_DISABLE_CLIP", "1")
    # Opt-in media upgrades must not leak from a developer's real environment into
    # default tests. Tests that exercise these gates set them explicitly.
    monkeypatch.delenv("EXOMEM_SEMANTIC_SEGMENTS", raising=False)
    monkeypatch.delenv("EXOMEM_VIDEO_SCENE_FRAMES", raising=False)
    # An exported EXOMEM_LOG_DIR must not decide where a test's records land.
    # `query_log._target` consults it per call and short-circuits ahead of the
    # module-level QUERIES_PATH/WRITES_PATH/READS_PATH that tests monkeypatch,
    # so three tests in test_query_log.py wrote into the operator's real log
    # directory and then failed reading their own tmp sidecar (#570). CI never
    # saw it -- the variable is unset there -- but the project's own Docker
    # images set it and the documented contract tells operators to export it,
    # so anyone running the suite on a configured machine got failures
    # unrelated to their change. Tests that exercise the override set it
    # themselves; a test-body or module-fixture setenv still wins over this.
    monkeypatch.delenv("EXOMEM_LOG_DIR", raising=False)
    # Same defect class as EXOMEM_LOG_DIR above, one layer deeper. An exported
    # EXOMEM_VAULT_PATH is the documented way to point the CLI and the service
    # at a real vault, and `LeaseManager._receipt_vault_root` falls back to it
    # whenever a mutation names no vault of its own. So on a configured machine
    # `_durable_graph_outcome` read the OPERATOR'S live vault and stamped its
    # graph state onto a terminal the test asserts is bare -- five
    # test_writer_lease.py tests failed that way, in isolation, on a checkout
    # with no defect in it.
    #
    # Worse than a false failure: the ambient value made every unscoped test a
    # reader of real user data, and CI never sees it because the variable is
    # unset there. The `vault` fixture sets it explicitly for tests that want
    # one, and autouse setup runs first, so that setenv still wins.
    monkeypatch.delenv("EXOMEM_VAULT_PATH", raising=False)
    # The watcher now starts independently of embeddings (it maintains the
    # freshness/inbound registries too), so build_server would spawn a real
    # watchdog observer in the suite without this. Watcher tests opt back in.
    monkeypatch.setenv("EXOMEM_DISABLE_FILE_WATCHER", "1")
    # Don't spawn the mode-config watch daemon from build_server in the suite; mode-watch
    # tests drive it directly.
    monkeypatch.setenv("EXOMEM_DISABLE_MODE_WATCH", "1")
    # The corpus-context cache invalidates on filesystem changes, which is
    # complete for production inputs — but tests also monkeypatch
    # corpus-affecting internals (access tiers, registries, walks), which no
    # filesystem census can observe. Default it off in the suite;
    # test_corpus_context_cache.py deletes this var to exercise it.
    monkeypatch.setenv("EXOMEM_DISABLE_CORPUS_CACHE", "1")
    # The projected-resolver warm thread is a production optimisation: it walks
    # the vault after an eviction so the next reader does not pay for it. In the
    # suite it would outlive the tmp vault that started it -- production is one
    # long-lived process, the suite is hundreds of vaults in one -- and touch
    # process-global caches from a test that has already finished.
    # `tests/test_recall_resolver_warm.py` deletes this var to exercise it.
    monkeypatch.setenv("EXOMEM_DISABLE_RESOLVER_WARM", "1")
    # A cold due-state projection now heals in a daemon thread so an ordinary
    # read never pays a vault-wide audit. Production is one long-lived process;
    # this suite creates hundreds of short-lived tmp vaults, so make that warm
    # synchronous by default and let its focused recovery tests opt back into
    # the real background path.
    monkeypatch.setenv("EXOMEM_SYNC_DUE_STATE_WARM", "1")


@pytest.fixture
def vault(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> Path:
    """Copy tests/fixtures/ into a tmp dir; return it as the vault root."""
    dest = tmp_path / "vault"
    shutil.copytree(FIXTURE_VAULT, dest)
    initialize_vault_state_offline(dest, source="canonical vault fixture")
    monkeypatch.setenv("EXOMEM_VAULT_PATH", str(dest))
    # Clear find's in-process cache so previous test runs don't bleed in.
    find_module.clear_cache()
    # Drop the process-shared embedding index memo — a stale instance keyed by a
    # prior tmp vault's path would otherwise persist across tests.
    embeddings_module.clear_embedding_indexes()
    return dest


@pytest.fixture
def source_schema(vault: Path) -> schema_module.SourceSchema:
    return schema_module.load_source_schema(vault)


class ScopeWalkSentinel:
    """Counts directory enumerations of a recall scope during one request.

    The read-path contract ("The Read Path Never Walks The Corpus") is
    structural, not a latency threshold: a stage either enumerated the scope or
    it did not. Every walk on the read path bottoms out in `os.scandir` or
    `os.listdir` on this interpreter — `Path.iterdir`, `Path.glob`/`rglob` and
    `os.walk` all route through `os.scandir` — so counting those two names
    catches a walk regardless of which spelling reintroduces it.

    A descriptor-relative enumeration (`os.scandir(fd)`, which `vault.py` uses)
    carries no path, so it is resolved through `/proc/self/fd` where that
    exists and otherwise recorded as unresolved rather than silently dropped:
    an enumeration the sentinel cannot attribute is its own state, not a pass.
    """

    def __init__(self, *scope_roots: Path) -> None:
        self._roots = tuple(os.path.realpath(root) for root in scope_roots)
        self.enumerated: list[str] = []
        self.unresolved: list[str] = []

    @property
    def count(self) -> int:
        return len(self.enumerated) + len(self.unresolved)

    def reset(self) -> None:
        self.enumerated.clear()
        self.unresolved.clear()

    def report(self) -> str:
        lines = [f"{len(self.enumerated)} scope enumerations"]
        lines += sorted(set(self.enumerated))
        if self.unresolved:
            lines.append(f"{len(self.unresolved)} unattributable enumerations")
            lines += sorted(set(self.unresolved))
        return "\n".join(lines)

    def _resolve(self, target: object) -> str | None:
        if isinstance(target, int):
            try:
                return os.path.realpath(f"/proc/self/fd/{target}")
            except OSError:
                self.unresolved.append(f"fd:{target}")
                return None
        try:
            return os.path.realpath(os.fspath(target))  # type: ignore[arg-type]
        except (TypeError, ValueError, OSError):
            self.unresolved.append(repr(target))
            return None

    def record(self, target: object) -> None:
        path = self._resolve(target)
        if path is None:
            return
        for root in self._roots:
            if path == root or path.startswith(root + os.sep):
                self.enumerated.append(path)
                return

    def install(self, monkeypatch: pytest.MonkeyPatch) -> None:
        real_scandir = os.scandir
        real_listdir = os.listdir

        def counting_scandir(path=".", *args, **kwargs):
            self.record(path)
            return real_scandir(path, *args, **kwargs)

        def counting_listdir(path=None, *args, **kwargs):
            self.record("." if path is None else path)
            return real_listdir(path, *args, **kwargs)

        monkeypatch.setattr(os, "scandir", counting_scandir)
        monkeypatch.setattr(os, "listdir", counting_listdir)


@pytest.fixture
def walk_sentinel(monkeypatch: pytest.MonkeyPatch):
    """Install a `ScopeWalkSentinel` over the given scope roots."""

    def _install(*scope_roots: Path) -> ScopeWalkSentinel:
        sentinel = ScopeWalkSentinel(*scope_roots)
        sentinel.install(monkeypatch)
        return sentinel

    return _install


@pytest.fixture
def warm_managed_cell(monkeypatch: pytest.MonkeyPatch):
    """Put a fixture vault in the state the live cell serves requests from.

    The read-path contracts govern the MANAGED reader: an offline/CLI caller
    keeps its exact source-walk fallback by design, so measuring either the
    walk sentinel or timing attribution against an unmanaged, cold vault
    measures the wrong path. This seeds the freshness registry, publishes the
    lexical catalogue, builds the reference sidecar once, and admits the
    request the way the server runtime does — the same recipe
    `tests/test_projection_lag_tolerance.py` uses, plus the sidecar.
    """

    def _warm(vault: Path) -> None:
        from exomem import embeddings, file_watcher, lexstore, memory_refs, readiness

        monkeypatch.setenv("EXOMEM_DISABLE_EMBEDDINGS", "1")
        monkeypatch.setattr(embeddings, "ranking_enabled", lambda: True)
        monkeypatch.setattr(readiness, "should_defer", lambda _component: False)

        file_watcher.FileWatcher(vault)._reconcile_once(seed=True)
        assert lexstore.get_store(vault).rebuild_atomic() is True
        assert lexstore.runtime_retrieval_catalog_proof(vault, schedule_repair=False) is not None
        # The reference sidecar is a maintained index too: `refs_for_paths`
        # scans the corpus exactly once, on first use or a schema upgrade, and
        # a live cell paid that long before any measured request.
        memory_refs.ReferenceIndex(vault).rebuild_all()

        monkeypatch.setattr(readiness, "runtime_managed", lambda: True)
        monkeypatch.setattr(
            readiness,
            "retrieval_admission",
            lambda _root=None: {"state": "ready", "admitted": True},
        )

    return _warm
