"""Generator determinism, template isolation, and corpus-level privacy."""

from __future__ import annotations

from pathlib import Path

import pytest

from exomem.public_artifact_privacy import scan_artifact

from membench.generate import GenerationError, generate_corpus
from membench.schema import ExpectedAnswer, ExpectedRecord
from membench.templates import registry
from membench.templates.base import Template

T00 = "t00_mini_smoke"


def _tree(root: Path) -> dict[str, bytes]:
    return {
        str(p.relative_to(root)): p.read_bytes() for p in sorted(root.rglob("*")) if p.is_file()
    }


def _dummy_template() -> Template:
    def build(ctx):  # type: ignore[no-untyped-def]
        entity = ctx.entity("concept", "science")
        source = ctx.source(2, f"{entity.canonical_name} note", lines=["A minor recorded fact."])
        claim = ctx.claim(entity, "noted_by", "field team", source)

        def expect(octx, query):  # type: ignore[no-untyped-def]
            return ExpectedRecord(query_id=query.query_id, answer=ExpectedAnswer(kind="none"))

        ctx.query("direct_recall", "Anything noted?", knowledge_week=4, expect=expect)
        _ = claim

    return Template(
        template_id="t99_dummy", family="query_behavior", summary="isolation probe",
        variants=1, build=build,
    )


def test_same_seed_regenerates_byte_identically(tmp_path: Path) -> None:
    first = generate_corpus(1, tmp_path / "a", template_ids=[T00])
    second = generate_corpus(1, tmp_path / "b", template_ids=[T00])
    assert first == second
    assert _tree(tmp_path / "a") == _tree(tmp_path / "b")


def test_different_seed_differs(tmp_path: Path) -> None:
    first = generate_corpus(1, tmp_path / "a", template_ids=[T00])
    second = generate_corpus(2, tmp_path / "b", template_ids=[T00])
    assert first != second


def test_template_isolation(tmp_path: Path) -> None:
    """Adding another template never perturbs T00's generated bytes."""

    alone = generate_corpus(1, tmp_path / "alone", template_ids=[T00])
    combined_templates = dict(registry())
    dummy = _dummy_template()
    combined_templates[dummy.template_id] = dummy
    generate_corpus(
        1, tmp_path / "combined", templates=combined_templates
    )
    alone_files = _tree(tmp_path / "alone")
    combined_files = _tree(tmp_path / "combined")
    for path, payload in alone_files.items():
        if path.startswith("sources/"):
            assert combined_files[path] == payload
    assert {e.path: e.bytes_sha256 for e in alone.artifacts}.items() <= {
        p: h
        for p, h in (
            (e["path"], e["bytes_sha256"])
            for e in __import__("json").loads(
                (tmp_path / "combined" / "manifest.json").read_text()
            )["artifacts"]
        )
    }.items()


def test_generated_corpus_passes_privacy_scan(tmp_path: Path) -> None:
    generate_corpus(1, tmp_path / "corpus", template_ids=[T00])
    findings = []
    for path in sorted((tmp_path / "corpus").rglob("*")):
        if path.is_file() and path.suffix in {".md", ".csv", ".txt", ".jsonl", ".json", ".yaml"}:
            findings.extend(scan_artifact(path, label=path.name))
    assert findings == []


def test_refuses_to_overwrite_nonempty_dir(tmp_path: Path) -> None:
    target = tmp_path / "corpus"
    generate_corpus(1, target, template_ids=[T00])
    with pytest.raises(GenerationError, match="not empty"):
        generate_corpus(1, target, template_ids=[T00])


def test_canary_purity_is_enforced(tmp_path: Path) -> None:
    manifest = generate_corpus(1, tmp_path / "corpus", template_ids=[T00])
    assert manifest.counts["queries"] >= 5 * 4  # 5 queries x 4 variants
