"""`exomem personalize` — turn a vault scan into a starter access policy.

Per-vault behavior is governed by ``Knowledge Base/_access.yaml`` (``readonly:`` /
``excluded:`` subtree lists, read by ``access.py``). Users shouldn't have to hand-write
that YAML: this scans the vault with the existing ``overview`` and proposes a policy for
the top-level folders that sit *beside* ``Knowledge Base/``, then merges it in
non-destructively.

No model, no network — just the bounded ``overview`` walk. It only ever ADDS the entries
it proposes (never removes a user's), is idempotent, and requires confirmation (or
``--yes``) before writing. It is deliberately NOT an MCP write tool: choosing what to
``exclude`` from search is a human-judgment call, and ``overview`` already gives an agent
the read-side picture.
"""

from __future__ import annotations

import argparse
import os
import sys
from dataclasses import asdict, dataclass, replace
from pathlib import Path

import yaml

from . import access as access_module
from . import overview as overview_module

# Classification of a top-level sibling folder.
CLASS_READONLY = "readonly"
CLASS_EXCLUDED = "excluded"
CLASS_UNMANAGED = "unmanaged"  # deliberately left OUT of _access.yaml

# Heuristic thresholds — measured signals only, never folder-name denylists.
BINARY_HEAVY_RATIO = 0.9  # no markdown AND >=90% binary -> asset dump -> excluded
JUNK_DOMINANT_RATIO = 0.5  # >=50% of a folder's files are junk -> excluded

_HEADER = (
    "# exomem access policy - generated by `exomem personalize`.\n"
    "# Governs per-subtree access for folders in this vault. Safe to hand-edit;\n"
    "# `exomem personalize` only ADDS entries it proposes, never removes yours.\n"
    "#\n"
    "#   readonly: findable via `find`, but every write is refused (hard guard).\n"
    "#   excluded: hidden from `find` / indexing AND unwritable.\n"
    "# Entries are subtree prefixes: a top-level sibling folder, or a KB-relative path.\n"
)


class PersonalizeError(Exception):
    """Structured failure (mirrors overview.OverviewError)."""

    def __init__(self, code: str, reason: str) -> None:
        super().__init__(f"{code}: {reason}")
        self.code = code
        self.reason = reason


@dataclass(frozen=True)
class FolderProposal:
    folder: str
    classification: str
    reason: str
    files: int
    markdown: int
    binary: int
    junk: int
    already_configured: str | None  # existing tier, or None if newly proposed


@dataclass(frozen=True)
class PersonalizeReport:
    vault: str
    access_path: str
    proposals: tuple[FolderProposal, ...]
    add_readonly: tuple[str, ...]
    add_excluded: tuple[str, ...]
    wrote: bool
    cap_omitted: int

    @property
    def needs_write(self) -> bool:
        return bool(self.add_readonly or self.add_excluded)

    @property
    def unchanged(self) -> bool:
        return not self.needs_write

    def as_dict(self) -> dict:
        return {
            "vault": self.vault,
            "access_path": self.access_path,
            "proposals": [asdict(p) for p in self.proposals],
            "add_readonly": list(self.add_readonly),
            "add_excluded": list(self.add_excluded),
            "wrote": self.wrote,
            "cap_omitted": self.cap_omitted,
        }


# --- pure core -------------------------------------------------------------


def _sibling_signals(scan: dict) -> dict[str, dict]:
    """Top-level folder name -> ``{files, markdown, binary, junk}``.

    Reads depth-1 ``tree`` entries (excluding ``Knowledge Base``) and attributes junk
    (sync-conflicts + zero-byte files) to a folder by path prefix. ``overview`` has
    already dropped ``.git``/``node_modules``/dot-dirs, so those never appear here.
    """
    junk = scan.get("junk", {})
    junk_paths = list(junk.get("sync_conflicts", [])) + list(junk.get("zero_byte", []))
    signals: dict[str, dict] = {}
    for entry in scan.get("tree", []):
        if entry.get("depth") != 1:
            continue
        name = entry.get("path", "")
        if not name or name == "Knowledge Base":
            continue
        junk_count = sum(1 for jp in junk_paths if jp == name or jp.startswith(name + "/"))
        signals[name] = {
            "files": entry.get("files_recursive", 0),
            "markdown": entry.get("markdown", 0),
            "binary": entry.get("binary", 0),
            "junk": junk_count,
        }
    return signals


def classify_siblings(scan: dict, existing: dict[str, list[str]]) -> list[FolderProposal]:
    """Classify each top-level sibling folder. Pure — feed it a synthetic ``overview``
    dict in tests. ``existing`` is ``access._load_config()`` output; already-configured
    folders are reported but never re-proposed."""
    readonly = set(existing.get("readonly", []))
    excluded = set(existing.get("excluded", []))
    proposals: list[FolderProposal] = []
    for name, s in sorted(_sibling_signals(scan).items()):
        files, md, binary, junk = s["files"], s["markdown"], s["binary"], s["junk"]
        common = dict(files=files, markdown=md, binary=binary, junk=junk)
        if name in excluded:
            proposals.append(FolderProposal(name, CLASS_EXCLUDED, "already excluded", already_configured=CLASS_EXCLUDED, **common))
        elif name in readonly:
            proposals.append(FolderProposal(name, CLASS_READONLY, "already readonly", already_configured=CLASS_READONLY, **common))
        elif files == 0:
            proposals.append(FolderProposal(name, CLASS_UNMANAGED, "empty - nothing to govern", already_configured=None, **common))
        elif junk >= JUNK_DOMINANT_RATIO * files:
            proposals.append(FolderProposal(name, CLASS_EXCLUDED, "junk-dominant (sync-conflict / zero-byte)", already_configured=None, **common))
        elif md == 0 and binary >= BINARY_HEAVY_RATIO * files:
            proposals.append(FolderProposal(name, CLASS_EXCLUDED, "binary-heavy, no markdown - asset dump", already_configured=None, **common))
        else:
            proposals.append(FolderProposal(name, CLASS_READONLY, "hand-authored input - findable, write-protected", already_configured=None, **common))
    return proposals


def merge_access_yaml(existing_text: str | None, add_readonly: list[str], add_excluded: list[str]) -> str:
    """Return new ``_access.yaml`` text: existing data + de-duped additions, sorted for
    byte-stable idempotent output. Non-destructive — preserves existing entries and any
    unknown top-level keys."""
    data: dict = {}
    if existing_text:
        loaded = yaml.safe_load(existing_text)
        if isinstance(loaded, dict):
            data = loaded

    def _merge(key: str, additions: list[str]) -> None:
        current = [str(x) for x in (data.get(key) or [])]
        for item in additions:
            if item not in current:
                current.append(item)
        if current:
            data[key] = current

    _merge("readonly", add_readonly)
    _merge("excluded", add_excluded)

    # Deterministic emission: readonly, then excluded, then any unknown keys — each
    # managed list sorted so re-running yields byte-identical output.
    ordered: dict = {}
    for key in ("readonly", "excluded"):
        if data.get(key):
            ordered[key] = sorted(data[key])
    for key in sorted(data):
        if key not in ordered and data.get(key) not in (None, [], {}):
            ordered[key] = data[key]

    body = yaml.safe_dump(ordered, sort_keys=False, default_flow_style=False, allow_unicode=True)
    return _HEADER + "\n" + body


# --- I/O + orchestration ---------------------------------------------------


def _vault_default() -> str | None:
    return os.environ.get("EXOMEM_VAULT_PATH")


def scan_and_classify(vault: str | Path, *, overview_fn=overview_module.overview) -> PersonalizeReport:
    """Scan and classify — never writes. Requires an initialized ``Knowledge Base/``
    (that's where ``_access.yaml`` lives), else raises ``PersonalizeError('NO_KB')``."""
    vault_path = Path(vault).expanduser()
    if not (vault_path / "Knowledge Base").is_dir():
        raise PersonalizeError("NO_KB", f"no Knowledge Base/ under {vault_path} - run `exomem init` first")
    scan = overview_fn(vault_path)
    existing = access_module._load_config(vault_path)
    proposals = classify_siblings(scan, existing)
    add_readonly = tuple(
        p.folder for p in proposals if p.classification == CLASS_READONLY and p.already_configured is None
    )
    add_excluded = tuple(
        p.folder for p in proposals if p.classification == CLASS_EXCLUDED and p.already_configured is None
    )
    root_entry = next((e for e in scan.get("tree", []) if e.get("path") == ""), {})
    return PersonalizeReport(
        vault=str(vault_path),
        access_path=str(access_module.access_config_path(vault_path)),
        proposals=tuple(proposals),
        add_readonly=add_readonly,
        add_excluded=add_excluded,
        wrote=False,
        cap_omitted=root_entry.get("children_omitted", 0),
    )


def write_access_yaml(report: PersonalizeReport) -> PersonalizeReport:
    """Write/merge the proposed entries into ``_access.yaml`` (atomic). No-op (returns
    the report unchanged) when there is nothing to add."""
    if not report.needs_write:
        return report
    path = Path(report.access_path)
    existing_text = path.read_text(encoding="utf-8") if path.exists() else None
    new_text = merge_access_yaml(existing_text, list(report.add_readonly), list(report.add_excluded))
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(new_text, encoding="utf-8")
    os.replace(tmp, path)
    return replace(report, wrote=True)


def personalize(vault: str | Path, *, apply: bool = True, overview_fn=overview_module.overview) -> PersonalizeReport:
    """Scan, classify, and (when ``apply`` and there's something to add) write."""
    report = scan_and_classify(vault, overview_fn=overview_fn)
    if apply and report.needs_write:
        report = write_access_yaml(report)
    return report


def _ask_yn(input_fn, prompt: str, default: bool) -> bool:
    suffix = " [Y/n] " if default else " [y/N] "
    answer = input_fn(prompt + suffix).strip().lower()
    if not answer:
        return default
    return answer.startswith("y")


def _render_proposals(report: PersonalizeReport, print_fn) -> None:
    for p in report.proposals:
        if p.already_configured is None and p.classification != CLASS_UNMANAGED:
            print_fn(f"  {p.folder}/  -> {p.classification}  ({p.reason})")
    if report.cap_omitted:
        print_fn(
            f"  note: {report.cap_omitted} more top-level folder(s) beyond the scan cap "
            "- re-run or add to _access.yaml by hand."
        )


def run_personalize(
    *,
    vault: str | Path,
    yes: bool = False,
    dry_run: bool = False,
    input_fn=input,
    print_fn=print,
    overview_fn=overview_module.overview,
) -> int:
    """Interactive converger for the CLI. Returns a process exit code."""
    try:
        report = scan_and_classify(vault, overview_fn=overview_fn)
    except PersonalizeError as e:
        print_fn(f"personalize: {e}")
        return 1
    if not report.needs_write:
        print_fn("personalize: nothing to govern - every sibling folder is already covered or empty.")
        return 0
    print_fn(f"Proposed access policy for {report.access_path}:")
    _render_proposals(report, print_fn)
    if dry_run:
        print_fn("personalize: --dry-run, nothing written.")
        return 0
    if not yes and not _ask_yn(input_fn, "Write these entries to _access.yaml?", True):
        print_fn("personalize: declined, nothing written.")
        return 0
    done = write_access_yaml(report)
    print_fn(
        f"personalize: wrote {len(done.add_readonly)} readonly + {len(done.add_excluded)} "
        f"excluded to {done.access_path}"
    )
    return 0


def personalize_main(argv: list[str]) -> int:
    parser = argparse.ArgumentParser(
        prog="exomem personalize",
        description=(
            "Scan a vault and generate a starter Knowledge Base/_access.yaml - classify "
            "top-level sibling folders as readonly/excluded so exomem knows what is "
            "read-only input. Non-destructive; only adds entries it proposes."
        ),
    )
    parser.add_argument("--vault", help="Vault root (default: $EXOMEM_VAULT_PATH).")
    parser.add_argument("--yes", action="store_true", help="Apply proposals without prompting.")
    parser.add_argument("--dry-run", action="store_true", help="Show the proposal; write nothing.")
    parser.add_argument("--json", action="store_true", help="Emit the report as JSON (no prompt).")
    args = parser.parse_args(argv)
    if args.yes and not args.vault:
        parser.error("--yes requires --vault")
    vault = args.vault or _vault_default()
    if not vault:
        parser.error("set --vault or $EXOMEM_VAULT_PATH")

    if args.json:
        import json

        try:
            report = personalize(vault, apply=not args.dry_run)
        except PersonalizeError as e:
            print(f"personalize: {e}", file=sys.stderr)
            return 1
        print(json.dumps(report.as_dict(), indent=2))
        return 0
    return run_personalize(vault=vault, yes=args.yes, dry_run=args.dry_run)
