"""Derive the benchmark-harness test-module list for the CI harness tier.

The PR test suite runs as two tiers (`core-tests` and `harness-tests` in
`.github/workflows/ci.yml`). The harness tier is exactly the test modules that
import the benchmark harness packages living under `benchmarks/` (reached via
the guarded `sys.path` insert in `tests/conftest.py`) or the shared
`tests/benchmark_capabilities.py` helper. Those modules carry a measured
fixed cost per test from harness environment/contract capture, so they are
sharded separately from the core suite.

The checked-in list is `tests/harness_modules.txt`; this script derives it by
import inspection (AST — module-level *and* function-level imports, plus
imports that go through same-directory test helpers), and
`tests/test_ci_reliability_contract.py` pins the checked-in file against this
derivation so the two cannot silently diverge.

Regenerate after adding or changing benchmark-importing test modules:

    uv run python scripts/generate_harness_modules.py --write

`tests/test_latency_gate.py` is deliberately excluded from the list even if it
qualifies: the nightly `retrieval-latency` job owns that file, and it runs in
neither PR tier.
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TESTS_DIR = REPO_ROOT / "tests"
OUTPUT_PATH = TESTS_DIR / "harness_modules.txt"

#: Top-level importable names of the benchmark harness. The packages live in
#: `benchmarks/` (on `sys.path` via tests/conftest.py) and are also reachable
#: spelled `benchmarks.<package>` — the repo root is on `sys.path` and
#: `benchmarks/` resolves as a namespace package, so
#: `from benchmarks.memorybench.traffic import …` is the same harness import
#: under its other name; the bare `benchmarks` prefix is therefore in the set.
#: `benchmark_capabilities` is the tests-local capability helper written for
#: the harness suites.
#: (`exomem.governance` is product code, not the harness, and tests-local
#: helpers such as `governance_projection_support` do not import benchmarks —
#: matching is by exact top-level import name, so neither is swept in.)
BENCHMARK_PACKAGES = frozenset(
    {
        "benchmarks",
        "lme",
        "membench",
        "memorybench",
        "epistemic",
        "protocol",
        "equivalence",
        "benchmark_capabilities",
    }
)

#: Nightly-owned modules excluded from both PR tiers regardless of imports.
NIGHTLY_OWNED = frozenset({"tests/test_latency_gate.py"})

HEADER = """\
# Benchmark-harness test modules (the CI `harness-tests` tier).
# Generated by scripts/generate_harness_modules.py — do not edit by hand:
#     uv run python scripts/generate_harness_modules.py --write
# Pinned against the derivation by tests/test_ci_reliability_contract.py.
"""


def _imported_top_level_names(path: Path) -> set[str]:
    """Every top-level name imported by *path*, at any nesting depth."""
    try:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
    except SyntaxError:
        return set()
    names: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                names.add(alias.name.split(".")[0])
        elif isinstance(node, ast.ImportFrom):
            if node.level == 0 and node.module:
                names.add(node.module.split(".")[0])
    return names


def derive_harness_modules(tests_dir: Path = TESTS_DIR) -> list[str]:
    """Relative POSIX paths of every harness-importing test module, sorted.

    A test module qualifies when it imports a benchmark package directly, or
    imports a tests-local helper module (same directory, or the tests root)
    that transitively does. Helpers are the non-test ``.py`` files pytest's
    rootdir ``sys.path`` handling makes importable next to the tests.
    """
    modules = [
        path
        for path in sorted(tests_dir.rglob("*.py"))
        if path.name != "conftest.py"
    ]
    imports = {path: _imported_top_level_names(path) for path in modules}
    by_dir: dict[Path, dict[str, Path]] = {}
    for path in modules:
        by_dir.setdefault(path.parent, {})[path.stem] = path

    def local_helper(path: Path, name: str) -> Path | None:
        for directory in (path.parent, tests_dir):
            helper = by_dir.get(directory, {}).get(name)
            if helper is not None and helper != path:
                return helper
        return None

    qualifies: dict[Path, bool] = {}

    def _qualifies(path: Path, active: frozenset[Path]) -> bool:
        if path in qualifies:
            return qualifies[path]
        if path in active:
            return False  # import cycle between helpers; decided elsewhere
        verdict = False
        for name in imports[path]:
            if name in BENCHMARK_PACKAGES:
                verdict = True
                break
            helper = local_helper(path, name)
            if helper is not None and _qualifies(helper, active | {path}):
                verdict = True
                break
        qualifies[path] = verdict
        return verdict

    selected: list[str] = []
    for path in modules:
        if not path.name.startswith("test_"):
            continue
        rel = path.relative_to(REPO_ROOT).as_posix()
        if rel in NIGHTLY_OWNED:
            continue
        if _qualifies(path, frozenset()):
            selected.append(rel)
    return sorted(selected)


def render(modules: list[str]) -> str:
    return HEADER + "".join(f"{module}\n" for module in modules)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--write",
        action="store_true",
        help=f"write the derived list to {OUTPUT_PATH.relative_to(REPO_ROOT).as_posix()}",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit 1 if the checked-in list differs from the derivation",
    )
    args = parser.parse_args(argv)

    modules = derive_harness_modules()
    content = render(modules)
    if args.write:
        OUTPUT_PATH.write_text(content, encoding="utf-8", newline="\n")
        print(f"wrote {len(modules)} modules to {OUTPUT_PATH}")
        return 0
    if args.check:
        current = OUTPUT_PATH.read_text(encoding="utf-8") if OUTPUT_PATH.is_file() else ""
        if current != content:
            print(
                "tests/harness_modules.txt is stale; regenerate with "
                "`uv run python scripts/generate_harness_modules.py --write`",
                file=sys.stderr,
            )
            return 1
        print(f"tests/harness_modules.txt is current ({len(modules)} modules)")
        return 0
    sys.stdout.write(content)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
