#!/bin/sh
# One-line bootstrap for exomem — macOS-first, also works on Linux.
#
# Usage (paste into Terminal):
#   curl -fsSL https://raw.githubusercontent.com/Artexis10/exomem/main/scripts/install.sh | sh
#
# What this does, in order:
#   1. Installs uv (the Python tool manager exomem is published through) if
#      it isn't already on PATH.
#   2. Installs exomem itself with `uv tool install exomem`.
#   3. Runs the interactive `exomem setup` wizard — or, if this shell has no
#      real terminal attached to prompt on, prints the exact command to run
#      next instead of guessing.
#
# Safe to run more than once: every step below only acts when it's not
# already done, matching `exomem setup`'s own idempotent design.
#
# POSIX sh only (no bashisms) so it runs under macOS's default /bin/sh as
# well as dash-based Linux shells.

set -eu

# ---------------------------------------------------------------------------
# Pretty-printing — only colorize when stdout is a real terminal.
# ---------------------------------------------------------------------------
if [ -t 1 ]; then
    BOLD='\033[1m'
    GREEN='\033[32m'
    YELLOW='\033[33m'
    RED='\033[31m'
    RESET='\033[0m'
else
    BOLD=''
    GREEN=''
    YELLOW=''
    RED=''
    RESET=''
fi

info() { printf '%s==>%s %s\n' "$BOLD" "$RESET" "$1"; }
ok()   { printf '%s==>%s %s\n' "$GREEN" "$RESET" "$1"; }
warn() { printf '%s==>%s %s\n' "$YELLOW" "$RESET" "$1" >&2; }

# die MESSAGE [HINT] — print a plain-language failure and exit, never a
# raw stack trace or bare command output.
die() {
    printf '\n%s%s%s\n' "$RED" "exomem install failed: $1" "$RESET" >&2
    if [ -n "${2:-}" ]; then
        printf '%s\n' "$2" >&2
    fi
    exit 1
}

# add_local_bin_to_path — uv (and `uv tool install`) both default to
# ~/.local/bin for the binaries they place; make sure this shell can see it
# without waiting for a new terminal.
add_local_bin_to_path() {
    case ":$PATH:" in
        *":$HOME/.local/bin:"*) ;;
        *) PATH="$HOME/.local/bin:$PATH" ;;
    esac
}

have_uv() { command -v uv >/dev/null 2>&1; }

install_uv() {
    info "Installing uv (the Python tool manager exomem needs)..."
    if ! command -v curl >/dev/null 2>&1; then
        die "curl is required but wasn't found." \
            "Install curl (on a fresh Mac: run 'xcode-select --install' in Terminal), then re-run this script."
    fi

    installer_script=$(curl -LsSf https://astral.sh/uv/install.sh) || die \
        "Couldn't download the uv installer from astral.sh." \
        "Check your internet connection and try again, or see https://docs.astral.sh/uv/getting-started/installation/ for a manual install."

    if ! printf '%s\n' "$installer_script" | sh; then
        die "The uv installer script ran but reported an error." \
            "See https://docs.astral.sh/uv/getting-started/installation/ for manual install steps."
    fi

    # New shells pick uv up automatically; make it visible in THIS one too.
    if [ -f "$HOME/.local/bin/env" ]; then
        # shellcheck disable=SC1091  # generated by the uv installer at runtime, not part of this repo
        . "$HOME/.local/bin/env"
    fi
    add_local_bin_to_path
    export PATH

    have_uv || die "uv still isn't on PATH after installing it." \
        "Open a new terminal window and re-run this script, or run: source \"\$HOME/.local/bin/env\""
}

# ---------------------------------------------------------------------------
# 1. uv
# ---------------------------------------------------------------------------
info "exomem install — this sets up the exomem MCP server and its Knowledge Base wizard."
echo

if have_uv; then
    uv_version=$(uv --version 2>/dev/null || echo "version unknown")
    ok "uv is already installed ($uv_version)."
else
    install_uv
    ok "uv installed."
fi

# ---------------------------------------------------------------------------
# 2. exomem
# ---------------------------------------------------------------------------
info "Installing exomem (first time may take a minute)..."
if ! uv tool install exomem; then
    die "'uv tool install exomem' failed." \
        "Check your internet connection, then try running that command by hand to see the full error."
fi
ok "exomem is installed."

add_local_bin_to_path
export PATH

if ! command -v exomem >/dev/null 2>&1; then
    warn "exomem installed, but this shell can't see the 'exomem' command yet."
    echo
    echo "Open a new terminal window, then run:"
    echo
    echo "    exomem setup"
    echo
    exit 0
fi

# ---------------------------------------------------------------------------
# 3. exomem setup
# ---------------------------------------------------------------------------
echo
info "Next: the setup wizard asks for a notes folder (an existing Obsidian vault,"
info "or any folder to use as one) and connects exomem to Claude Code."
echo

can_prompt=0
if [ -t 0 ]; then
    can_prompt=1
elif [ -c /dev/tty ] && (exec < /dev/tty) 2>/dev/null; then
    # Piped in via 'curl | sh': stdin is the script itself, not the keyboard.
    # A real terminal is still attached, though, so reattach the wizard's
    # input to it and let it prompt normally.
    exec < /dev/tty
    can_prompt=1
fi

if [ "$can_prompt" = 1 ]; then
    exomem setup
else
    warn "No interactive terminal detected here, so the setup wizard needs to be run by hand."
    echo
    echo "Run this next:"
    echo
    echo "    exomem setup"
    echo
    echo "(Non-interactive alternative: exomem setup --yes --vault \"/path/to/your/Obsidian\" --lean)"
fi
