#!/usr/bin/env python3
"""Stage-by-stage latency of one guarded ``record_memory`` append.

Diagnosis harness, not a benchmark gate. It builds a synthetic Records collection
(invented data, temp vault, temp state root) at several sizes and times single
appends through the real dispatcher (``writer_lease.invoke_command``), so the
idempotency ledger, the mutation boundary and the post-commit index fan-out are
all on the measured path. Explicit wrappers accumulate per-stage wall time, and
the product's own ``call_spans`` are collected alongside them.

    uv run python scripts/measure-records-append-latency.py \
        --sizes 10,100,1000 --appends 30 --out records-append-latency.json

Nothing here touches a live service or a real state root: the child process
points ``EXOMEM_STATE_ROOT``, ``XDG_STATE_HOME`` and the writer-lease directory
at a temp tree and disables embedding models and background watchers.
"""

from __future__ import annotations

import argparse
import contextlib
import cProfile
import datetime as dt
import functools
import io
import json
import os
import pstats
import shutil
import subprocess
import sys
import tempfile
import threading
import time
import uuid
from collections import defaultdict
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
COLLECTION = "Knowledge Base/Records/Field Log/_collection.md"

MANIFEST = """---
type: collection
exomem_id: 6a7b8c9d-1111-4222-8333-444455556666
title: Field log
semantic_profile: records
collection_version: 1
schema_version: 1
lifecycle: active
storage:
  strategy: markdown-items
  source: Items
  format_version: 1
item_schema:
  natural_key: [observed_on, subject]
  fields:
    observed_on:
      type: date
      required: true
    subject:
      type: string
      required: true
    status:
      type: string
    note:
      type: string
    provenance:
      type: string
    tags:
      type: array
      items:
        type: string
item_filename:
  version: 1
  fields: [observed_on, subject]
item_presentation:
  version: 1
  title: subject
  summary: [observed_on, status]
  long_text: [note, provenance]
---

Synthetic collection for latency measurement.
"""


def _item(index: int) -> dict[str, object]:
    day = dt.date(1990, 1, 1) + dt.timedelta(days=index)
    return {
        "observed_on": day.isoformat(),
        "subject": f"Widget {index:05d}",
        "status": "logged",
        "note": f"Synthetic observation number {index}. " * 3,
        "provenance": "Generated by the latency harness.",
        "tags": ["alpha", "beta"],
    }


def _pct(values: list[float], q: float) -> float:
    ordered = sorted(values)
    if not ordered:
        return 0.0
    rank = (len(ordered) - 1) * q
    lo, hi = int(rank), min(int(rank) + 1, len(ordered) - 1)
    return ordered[lo] + (ordered[hi] - ordered[lo]) * (rank - lo)


# --------------------------------------------------------------------------- child


class Stages:
    """Inclusive wall time per named stage, outermost entry only, main thread only."""

    def __init__(self) -> None:
        self.main = threading.get_ident()
        self.depth: dict[str, int] = defaultdict(int)
        self.total: dict[str, float] = defaultdict(float)
        self.calls: dict[str, int] = defaultdict(int)

    def reset(self) -> None:
        self.total.clear()
        self.calls.clear()

    def wrap(self, owner: object, attr: str, name: str) -> None:
        original = getattr(owner, attr)
        stages = self

        @functools.wraps(original)
        def timed(*args, **kwargs):  # type: ignore[no-untyped-def]
            if threading.get_ident() != stages.main:
                return original(*args, **kwargs)
            stages.calls[name] += 1
            stages.depth[name] += 1
            start = time.perf_counter()
            try:
                return original(*args, **kwargs)
            finally:
                stages.depth[name] -= 1
                if stages.depth[name] == 0:
                    stages.total[name] += time.perf_counter() - start

        setattr(owner, attr, timed)

    def wrap_cm(self, owner: object, attr: str, name: str) -> None:
        """Time a @contextmanager's acquisition and its release separately."""
        original = getattr(owner, attr)
        stages = self

        @functools.wraps(original)
        @contextlib.contextmanager
        def timed(*args, **kwargs):  # type: ignore[no-untyped-def]
            manager = original(*args, **kwargs)
            start = time.perf_counter()
            value = manager.__enter__()
            stages.total[f"{name}.enter"] += time.perf_counter() - start
            stages.calls[f"{name}.enter"] += 1
            try:
                yield value
            except BaseException:
                if not manager.__exit__(*sys.exc_info()):
                    raise
            else:
                start = time.perf_counter()
                manager.__exit__(None, None, None)
                stages.total[f"{name}.exit"] += time.perf_counter() - start
                stages.calls[f"{name}.exit"] += 1

        setattr(owner, attr, timed)


def _child(args: argparse.Namespace) -> dict[str, object]:
    size = args.size
    tmp = Path(tempfile.mkdtemp(prefix="exomem-append-latency-"))
    os.environ.update(
        {
            "XDG_STATE_HOME": str(tmp / "xdg"),
            "EXOMEM_STATE_ROOT": str(tmp / "state"),
            "EXOMEM_WRITER_LEASE_STATE_DIR": str(tmp / "state" / "writer-lease"),
            "EXOMEM_CONFIG_PATH": str(tmp / "no-such-config.json"),
            "EXOMEM_DISABLE_EMBEDDINGS": "1",
            "EXOMEM_DISABLE_RELEVANCE_CHECK": "1",
            "EXOMEM_DISABLE_WARMUP": "1",
            "EXOMEM_DISABLE_FILE_WATCHER": "1",
            "EXOMEM_DISABLE_MODE_WATCH": "1",
            "EXOMEM_DISABLE_MEDIA_EXTRACTION": "1",
            "EXOMEM_DISABLE_CLIP": "1",
            "EXOMEM_DISABLE_RANKING_CONFIG": "1",
            "CUDA_VISIBLE_DEVICES": "",
        }
    )
    vault = tmp / "vault"
    (vault / "Knowledge Base").mkdir(parents=True)
    os.environ["EXOMEM_VAULT_PATH"] = str(vault)
    sys.path.insert(0, str(REPO / "src"))

    from exomem import (
        call_spans,
        commands,
        graph_sync,
        index_sync,
        record_formats,
        record_governance,
        records,
        reserved_paths,
        state_migration,
        writer_lease,
    )
    from exomem import record_memory as record_memory_module
    from exomem import structured_collections as collections
    from exomem import vault as vault_module
    from exomem.governance import egress

    authority = state_migration.assert_offline_migration_authority(source="latency harness")
    state_migration.migrate_vault_state_offline(vault, authority=authority)
    state_migration.reset_state_resolution_cache_for_tests()

    (vault / "Knowledge Base" / "log.md").write_text("# Activity\n", encoding="utf-8")
    manifest_file = vault / COLLECTION
    manifest_file.parent.mkdir(parents=True)
    manifest_file.write_text(MANIFEST, encoding="utf-8")
    (manifest_file.parent / "Items").mkdir()
    manifest = collections.load_manifest(vault, manifest_file)

    # Seed `size` items rendered exactly as the writer renders them. Going through
    # append_record for each would be O(size^2) and is the thing being measured.
    occupied: set[str] = set()
    started = time.perf_counter()
    for index in range(size):
        values = _item(index)
        key = collections.derived_item_key(manifest, values) or str(uuid.uuid4())
        text = record_formats.render_markdown_item(
            manifest, values, key, "", uuid.uuid4().hex[:24], resolve_relationship=None
        )
        relative = collections.render_item_path(manifest, values, key, occupied_paths=occupied)
        occupied.add(relative)
        (vault / relative).write_text(text, encoding="utf-8")
    seed_seconds = time.perf_counter() - started

    command = next(c for c in commands.PRODUCT_COMMANDS if c.name == "record_memory")
    stages = Stages()
    stages.wrap(record_memory_module, "_validate_arguments", "validate.arguments")
    stages.wrap(records, "_validate_values", "validate.values")
    stages.wrap(records, "_validate_why", "validate.why_body")
    stages.wrap(records, "_validate_body", "validate.why_body")
    stages.wrap(record_governance, "resolve_collection_for_mutation", "collection.resolve")
    stages.wrap(record_governance, "require_records_profile", "collection.profile")
    stages.wrap_cm(writer_lease.LeaseManager, "mutation_guard", "boundary")
    stages.wrap(records, "_load_guarded_manifest", "guard.manifest_load")
    stages.wrap(collections, "parse_manifest_bytes", "guard.manifest_parse")
    stages.wrap(record_governance, "require_mutation_visibility", "authz.visibility")
    stages.wrap(record_governance, "precommit_authorize_mutation", "authz.precommit")
    stages.wrap(record_formats, "load_adapter", "guard.load_adapter")
    stages.wrap(record_formats.MarkdownItemsAdapter, "read", "guard.snapshot_read")
    stages.wrap(records, "_natural_key_twins", "guard.natural_key_twins")
    stages.wrap(records, "_new_item_path", "write.new_item_path")
    stages.wrap(records, "_items_container_hash", "guard.after_container_hash")
    stages.wrap(record_formats, "render_markdown_item", "render.item")
    stages.wrap(record_formats, "_item_presentation_block", "render.presentation_block")
    stages.wrap(record_formats, "render_manifest_audit_head", "render.manifest_head")
    stages.wrap(records, "_audit_body", "audit.body")
    stages.wrap(records, "_plan_required_audit", "audit.plan")
    stages.wrap(vault_module, "batch_atomic_write", "write.batch_atomic_write")
    stages.wrap(vault_module, "post_commit_batch_fanout", "write.post_commit_fanout")
    stages.wrap(index_sync, "upsert_after_write", "index.upsert_after_write")
    stages.wrap(records, "_due_state_carrier", "post.due_state_carrier")
    stages.wrap(records, "_capture_sweep_carrier", "post.capture_sweep_carrier")
    stages.wrap(writer_lease.IdempotencyStore, "run", "ledger.run")
    stages.wrap(writer_lease.IdempotencyStore, "completed_terminal", "ledger.completed_terminal")
    stages.wrap(writer_lease, "_command_digest", "ledger.command_digest")
    stages.wrap(writer_lease, "_effective_idempotency_key", "ledger.effective_key")
    stages.wrap(writer_lease, "_drain_post_terminal_fanout", "post.terminal_fanout")
    stages.wrap(writer_lease, "_drain_post_terminal_housekeeping", "post.terminal_housekeeping")
    stages.wrap(egress, "postfilter", "response.egress_postfilter")
    stages.wrap(reserved_paths, "reserved_preflight", "request.reserved_preflight")
    stages.wrap(graph_sync, "status", "graph.status")
    stages.wrap(graph_sync, "join_registered_if_settled", "graph.join_registered")

    leaf_time = {"leaf": 0.0}
    original_leaf = command.leaf

    def timed_leaf(*a, **k):  # type: ignore[no-untyped-def]
        start = time.perf_counter()
        try:
            return original_leaf(*a, **k)
        finally:
            leaf_time["leaf"] = time.perf_counter() - start

    from dataclasses import replace

    timed_command = replace(command, leaf=timed_leaf)

    component_outcomes: dict[str, str] = {}
    timed_upsert = index_sync.upsert_after_write

    def spying_upsert(*a, **k):  # type: ignore[no-untyped-def]
        report = timed_upsert(*a, **k)
        for item in getattr(report, "components", ()):
            component_outcomes[str(item.component)] = str(item.outcome)
        return report

    index_sync.upsert_after_write = spying_upsert

    def invoke(**kwargs: object) -> tuple[float, object, list[dict[str, object]]]:
        token = f"harness-{uuid.uuid4().hex}"
        call_spans.MCP_CALL_TOKEN.set(token)
        start = time.perf_counter()
        result = writer_lease.invoke_command(timed_command, vault, **kwargs)
        wall = time.perf_counter() - start
        return wall, result, call_spans.pop_call_spans(token)

    def refresh_hash() -> tuple[float, str]:
        wall, result, _ = invoke(action="inspect", collection=COLLECTION)
        found = _find_container_hash(result)
        if found is None:
            raise RuntimeError("inspect did not surface a container hash")
        return wall, found

    def one_append(
        index: int, guarded: bool, expected: str | None
    ) -> tuple[float, dict[str, float], list[dict[str, object]]]:
        stages.reset()
        leaf_time["leaf"] = 0.0
        kwargs: dict[str, object] = {
            "action": "append",
            "collection": COLLECTION,
            "item": _item(size + index),
            "why": "latency measurement",
        }
        if guarded and expected is not None:
            kwargs["expected_container_hash"] = expected
        wall, result, spans = invoke(**kwargs)
        if not isinstance(result, dict) or result.get("outcome") != "committed":
            raise RuntimeError(f"append did not commit: {str(result)[:300]}")
        row = dict(stages.total)
        row["total"] = wall
        row["leaf"] = leaf_time["leaf"]
        row["dispatcher_outside_leaf"] = wall - leaf_time["leaf"]
        return wall, row, spans

    # Warm-up: imports, first-call caches, and one-time state directory creation.
    one_append(5000, False, None)

    def summarize(rows: list[dict[str, float]]) -> dict[str, dict[str, float]]:
        names = sorted({name for row in rows for name in row})
        return {
            name: {
                "p50_ms": round(1000 * _pct([r.get(name, 0.0) for r in rows], 0.5), 2),
                "p95_ms": round(1000 * _pct([r.get(name, 0.0) for r in rows], 0.95), 2),
            }
            for name in names
        }

    n = args.appends
    out: dict[str, object] = {"size": size, "appends": n, "seed_seconds": round(seed_seconds, 2)}

    # A: guarded append; the client pays a container-version read before every append.
    guarded_rows: list[dict[str, float]] = []
    span_rows: list[dict[str, float]] = []
    refresh_ms: list[float] = []
    walls: list[float] = []
    for index in range(n):
        refresh_wall, expected = refresh_hash()
        refresh_ms.append(refresh_wall)
        wall, row, spans = one_append(index, True, expected)
        walls.append(wall)
        guarded_rows.append(row)
        span_rows.append({str(s.get("name")): float(s.get("ms", 0)) / 1000 for s in spans})
    out["guarded_append"] = summarize(guarded_rows)
    out["guarded_call_spans"] = summarize(span_rows)
    out["guarded_append_wall_ms"] = {
        "p50": round(1000 * _pct(walls, 0.5), 2),
        "p95": round(1000 * _pct(walls, 0.95), 2),
    }
    out["guard_refresh_read_ms"] = {
        "p50": round(1000 * _pct(refresh_ms, 0.5), 2),
        "p95": round(1000 * _pct(refresh_ms, 0.95), 2),
    }
    out["guard_round_trip_ms"] = {
        "p50": round(1000 * (_pct(refresh_ms, 0.5) + _pct(walls, 0.5)), 2),
    }
    out["stage_calls_last_append"] = dict(stages.calls)
    out["index_component_outcomes"] = dict(component_outcomes)

    # B: unguarded append (no expected_container_hash) isolates the guard's own cost.
    walls_b: list[float] = []
    for index in range(n):
        wall, _row, _spans = one_append(n + index, False, None)
        walls_b.append(wall)
    out["unguarded_append_wall_ms"] = {
        "p50": round(1000 * _pct(walls_b, 0.5), 2),
        "p95": round(1000 * _pct(walls_b, 0.95), 2),
    }

    # C: one cProfile pass over a single guarded append.
    _, expected = refresh_hash()
    profile = cProfile.Profile()
    stages.reset()
    profile.enable()
    one_append(3 * n, True, expected)
    profile.disable()
    buffer = io.StringIO()
    pstats.Stats(profile, stream=buffer).sort_stats("cumulative").print_stats(r"exomem", 45)
    out["profile_cumulative"] = buffer.getvalue()
    buffer = io.StringIO()
    pstats.Stats(profile, stream=buffer).sort_stats("tottime").print_stats(25)
    out["profile_tottime"] = buffer.getvalue()

    shutil.rmtree(tmp, ignore_errors=True)
    return out


def _find_container_hash(value: object) -> str | None:
    if isinstance(value, dict):
        for key in ("expected_container_hash", "container_hash"):
            if isinstance(value.get(key), str):
                return value[key]  # type: ignore[no-any-return]
        for child in value.values():
            found = _find_container_hash(child)
            if found:
                return found
    elif isinstance(value, list):
        for child in value:
            found = _find_container_hash(child)
            if found:
                return found
    return None


# -------------------------------------------------------------------------- parent


def _parent(args: argparse.Namespace) -> int:
    results = []
    for size in [int(part) for part in args.sizes.split(",")]:
        print(f"== size {size} ==", file=sys.stderr, flush=True)
        completed = subprocess.run(
            [
                sys.executable,
                __file__,
                "--child",
                "--size",
                str(size),
                "--appends",
                str(args.appends),
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        sys.stderr.write(completed.stderr[-2000:])
        if completed.returncode != 0:
            print(completed.stdout[-2000:], file=sys.stderr)
            return completed.returncode
        marker = "RESULT-JSON:"
        line = next(
            row for row in reversed(completed.stdout.splitlines()) if row.startswith(marker)
        )
        results.append(json.loads(line[len(marker) :]))
        Path(args.out).write_text(json.dumps(results, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {args.out}", file=sys.stderr)
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--sizes", default="10,100,1000")
    parser.add_argument("--appends", type=int, default=30)
    parser.add_argument("--out", default="records-append-latency.json")
    parser.add_argument("--child", action="store_true", help=argparse.SUPPRESS)
    parser.add_argument("--size", type=int, default=0, help=argparse.SUPPRESS)
    args = parser.parse_args()
    if args.child:
        print("RESULT-JSON:" + json.dumps(_child(args)))
        return 0
    return _parent(args)


if __name__ == "__main__":
    raise SystemExit(main())
