{{- if not .Values.credentialsManagedExternally }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentialsSecretName }}
  labels:
    {{- include "exomem-cell.labels" . | nindent 4 }}
  annotations:
    exomem.io/populated-by: provisioner
    {{- include "exomem-cell.providerAnnotationsFor" (dict "root" . "key" "credentialSecret") | nindent 4 }}
type: Opaque
immutable: false
{{- end }}
