apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentialsSecretName }}
  labels:
    {{- include "exomem-cell.labels" . | nindent 4 }}
  annotations:
    exomem.io/populated-by: provisioner
type: Opaque
immutable: false
