apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.resourceName }}
  labels:
    {{- include "exomem-cell.labels" . | nindent 4 }}
  annotations:
    {{- include "exomem-cell.providerAnnotationsFor" (dict "root" . "key" "serviceAccount") | nindent 4 }}
automountServiceAccountToken: false
