apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.resourceName }}-data
  labels:
    {{- include "exomem-cell.labels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- include "exomem-cell.providerAnnotationsFor" (dict "root" . "key" "vaultPvc") | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  storageClassName: {{ .Values.storageClassName }}
  resources:
    requests:
      storage: {{ .Values.pvcSize }}
